name: release

on: 
  push:
    branches: 
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Run Deploy Hom
      run: echo "Deploy Hom"

    - name: Run Deploy Hom
      run: echo "Deploy Hom"
