name: validation

on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches: 
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Validation
      run: 
        cat ./readme.md
